name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ~/node_modules/.bin/wdio
      - uses: education/autograding@v1
